" Generated by vim-plug
" Mon Jul 25 03:24:32 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Dockerfile.vim'].commit = '2a31e6bcea5977209c05c728c4253d82fd873c82'
silent! let g:plugs['YouCompleteMe'].commit = '89bba25c96866662ca38c2428f73eb64b0351ba3'
silent! let g:plugs['ale'].commit = '80dcd648d389965603246c2c5a4554e3e4aa184c'
silent! let g:plugs['fzf'].commit = 'a06671b47f0284733c7edf7dae8f22f9758c8393'
silent! let g:plugs['fzf.vim'].commit = 'b23e4bb8f853cb9641a609c5c8545751276958b0'
silent! let g:plugs['rainbow'].commit = 'c18071e5c7790928b763c2e88c487dfc93d84a15'
silent! let g:plugs['reply.vim'].commit = 'f458f7c13cbd8eafaf9acd69e8eade71416338c5'
silent! let g:plugs['syntastic-local-eslint.vim'].commit = 'fd5da4df8ba032be411630b81770739f9846b078'
silent! let g:plugs['tabular'].commit = '339091ac4dd1f17e225fe7d57b48aff55f99b23a'
silent! let g:plugs['vim-airline'].commit = 'a306a7abfd8b4450fcfdc0384dadb996148d2c1b'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-anyfold'].commit = '3ed5d8ccbf0f5031f7c7d2be05aa7ddb4550dc5c'
silent! let g:plugs['vim-codefmt'].commit = '27e5ac299a0714025cc46fc1da11694a8662b058'
silent! let g:plugs['vim-elixir'].commit = 'ff7a1223dfc5386c41bb582039a90a262d488607'
silent! let g:plugs['vim-flake8'].commit = 'a99054ef98e8fdaefa1315af4649138bcadbfdf7'
silent! let g:plugs['vim-fugitive'].commit = '46652a304f0b89f36d70cee954d77e467ec0f6de'
silent! let g:plugs['vim-gitgutter'].commit = '18d12985ea6cb7ede59755ff4fd0a9fa1e6bf835'
silent! let g:plugs['vim-maktaba'].commit = 'f5127b339a9d776f220cc0393783c55def9d8ce0'
silent! let g:plugs['vim-markdown'].commit = '95e90840c45911b62261bae02e3ba2777877eaf5'
silent! let g:plugs['vim-monokai-pro'].commit = '05e534f9fea9a8e4cbf69a1523c785845deabe4e'
silent! let g:plugs['vim-multiple-cursors'].commit = '6456718e1d30b42c04b920c5413ca44f68f08759'
silent! let g:plugs['vim-slime'].commit = '0ea9b35882155996171fd15a5227e673ce2d2c60'
silent! let g:plugs['vim-surround'].commit = 'baf89ad26488f6a7665d51b986f5c7ad2d22b30b'
silent! let g:plugs['vim-templates'].commit = 'cf3218180fab9e463a331eb7e9fbbdef3f792133'
silent! let g:plugs['vim-terminal-help'].commit = '47d47061e771f4bb6db9067e21c0fd15939c5558'

PlugUpdate!

