on: [push]

jobs:
  build-dockerimage:
    runs-on: ubuntu-latest
    name: build-dockerimage
    steps:
      - name: Build docker image
        run: |
          ls
          docker build -t vimwithplug:test .
