on: 
  push:
    branches: [ main ]
jobs:
  build-dockerimage:
    runs-on: ubuntu-latest
    name: build-dockerimage
    steps:
      - name: Get git hash
        id: githash
        run: echo "::set-output name=git_hash::$GITHUB_SHA"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build to local
        run:
          docker build -t bidaya0/just-another-vim-image:${{ steps.githash.outputs.git_hash }} .
          docker build -t bidaya0/just-another-vim-image:latest .
          docker push bidaya0/just-another-vim-image:${{ steps.githash.outputs.git_hash }}
          docker push bidaya0/just-another-vim-image:latest
            #      - name: Build to local
            #        uses: docker/build-push-action@v2
            #        with:
            #          context: .
            #          load: true
            #          tags: |
            #            bidaya0/just-another-vim-image:${{ steps.githash.outputs.git_hash }}
            #            bidaya0/just-another-vim-image:latest
