on: 
  schedule:
  - cron: "0 0 * * *"
jobs:
  build-dockerimage:
    runs-on: ubuntu-latest
    name: build-dockerimage
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build to local
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: |
            bidaya0/just-another-vim-image:nightly-${{ steps.date.outputs.date }}
